version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ACME_API_KEY=${ACME_API_KEY:-acme_dev_test_key_123}
      - FMCSA_API_KEY=${FMCSA_API_KEY}
      - FMCSA_BASE_URL=${FMCSA_BASE_URL:-https://mobile.fmcsa.dot.gov/qc/services}
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./api/data:/app/api/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3